import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import { Roboto } from 'next/font/google';
import Header from "@/components/Header";

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Powerhouse",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={roboto.className}>
      <Header />
      {children}
      </body>
      </html>
  );
}
